<?php
/**
 * Vite asset loading
 *
 * In development, assets are served with HMR from the Vite dev server
 * (https://tailwind-wordpress.localhost:3009, started with `make vite-dev`).
 * In production, assets are read from the manifest generated by `make vite-build`.
 */

namespace App\Theme;

// Public host: what the browser resolves (dev-server asset URLs).
const VITE_DEV_HOST = 'tailwind-wordpress.localhost';
// Internal host: the `node` Docker Compose service, reachable from the `php` container.
const VITE_INTERNAL_HOST = 'node';
const VITE_DEV_PORT = 3009;
const VITE_ENTRY = 'assets/scripts/app.js';

function vite_dev_server_running(): bool
{
    static $running = null;

    if ($running !== null) {
        return $running;
    }

    $connection = @fsockopen(VITE_INTERNAL_HOST, VITE_DEV_PORT, $errno, $errstr, 0.2);

    $running = (bool) $connection;

    if ($connection) {
        fclose($connection);
    }

    return $running;
}

function vite_set_script_module(string $tag, string $handle, array $handles): string
{
    if (!in_array($handle, $handles, true)) {
        return $tag;
    }

    return str_replace(' src', ' type="module" src', $tag);
}

function enqueue_vite_assets(): void
{
    $is_dev = defined('WP_ENV') && WP_ENV === 'development' && vite_dev_server_running();

    if ($is_dev) {
        $dev_server = sprintf('https://%s:%d', VITE_DEV_HOST, VITE_DEV_PORT);
        $handles = ['vite-client', 'tailwind-theme-app'];

        wp_enqueue_script('vite-client', "{$dev_server}/@vite/client", [], null, false);
        wp_enqueue_script('tailwind-theme-app', "{$dev_server}/" . VITE_ENTRY, [], null, true);

        add_filter('script_loader_tag', function (string $tag, string $handle) use ($handles) {
            return vite_set_script_module($tag, $handle, $handles);
        }, 10, 2);

        return;
    }

    $manifest_path = get_template_directory() . '/dist/.vite/manifest.json';

    if (!file_exists($manifest_path)) {
        return;
    }

    $manifest = json_decode((string) file_get_contents($manifest_path), true);
    $entry = $manifest[VITE_ENTRY] ?? null;

    if (!$entry) {
        return;
    }

    $theme_uri = get_template_directory_uri();

    wp_enqueue_script('tailwind-theme-app', "{$theme_uri}/dist/{$entry['file']}", [], null, true);

    add_filter('script_loader_tag', function (string $tag, string $handle) {
        return vite_set_script_module($tag, $handle, ['tailwind-theme-app']);
    }, 10, 2);

    foreach ($entry['css'] ?? [] as $index => $css_file) {
        wp_enqueue_style("tailwind-theme-app-{$index}", "{$theme_uri}/dist/{$css_file}", [], null);
    }
}

add_action('wp_enqueue_scripts', __NAMESPACE__ . '\\enqueue_vite_assets');
